version: "3.9"

services:
  bot:
    image: ghcr.io/hblwrk/discord-bot-js:main
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
        reservations:
          cpus: "0.5"
          memory: 256M
    read_only: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "11312:11312"
    secrets:
      - production_discord_token
      - production_discord_clientID
      - production_discord_guildID
      - production_dracoon_password
      - production_healthcheck_port
      - production_hblwrk_NYSEAnnouncement_ChannelID
      - production_hblwrk_MNCAnnouncement_ChannelID
      - production_hblwrk_OtherAnnouncement_ChannelID

secrets:
  production_discord_token:
    external: true
  production_discord_clientID:
    external: true
  production_discord_guildID:
    external: true
  production_dracoon_password:
    external: true
  production_healthcheck_port:
    external: true
  production_hblwrk_NYSEAnnouncement_ChannelID:
    external: true
  production_hblwrk_MNCAnnouncement_ChannelID:
    external: true
  production_hblwrk_NYSEAnnouncement_ChannelID:
    external: true
  production_hblwrk_OtherAnnouncement_ChannelID:
    external: true
