version: "3.9"

secrets:
  discord_token:
    external: true
  discord_clientId:
    external: true
  discord_guildId:
    external: true

services:
  bot:
    image: ghcr.io/hblwrk/discord-bot-js:main
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
        reservations:
          cpus: "0.5"
          memory: 256M
    read_only: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    secrets:
      - discord_token
      - discord_clientId
      - discord_guildId
    ports:
      - "11312:11312"
